# Generated by Django 3.0.8 on 2020-12-07 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=8, max_digits=11)),
                ('lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('sight_time', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('brn', models.BooleanField(default=False)),
                ('red', models.BooleanField(default=False)),
                ('ylw', models.BooleanField(default=False)),
                ('wht', models.BooleanField(default=False)),
                ('blk', models.BooleanField(default=False)),
                ('gry', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Missing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=11)),
                ('lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('missing_time', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('brn', models.BooleanField(default=False)),
                ('red', models.BooleanField(default=False)),
                ('ylw', models.BooleanField(default=False)),
                ('wht', models.BooleanField(default=False)),
                ('blk', models.BooleanField(default=False)),
                ('gry', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
