# Generated by Django 3.0.8 on 2020-12-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentry', '0003_auto_20201208_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missing',
            name='blk',
        ),
        migrations.RemoveField(
            model_name='missing',
            name='brn',
        ),
        migrations.RemoveField(
            model_name='missing',
            name='gry',
        ),
        migrations.RemoveField(
            model_name='missing',
            name='red',
        ),
        migrations.RemoveField(
            model_name='missing',
            name='wht',
        ),
        migrations.RemoveField(
            model_name='missing',
            name='ylw',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='blk',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='brn',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='gry',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='red',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='wht',
        ),
        migrations.RemoveField(
            model_name='sighting',
            name='ylw',
        ),
        migrations.AlterField(
            model_name='missing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
