# Generated by Django 3.1.4 on 2020-12-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentry', '0004_auto_20201216_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
